#!/bin/bash

RED='tput setaf 1'
GREEN='tput setaf 2'
LBLUE='tput setaf 6'
NC='tput sgr0' # No Color

warn() {
    local message="${1:-""}"
    echo "$RED$message$NC"
    return 0
}

success() {
    local message="${1:-""}"
    echo "$GREEN$message$NC"
    return 0
}

to_action() {
    local message="${1:-""}"
    echo "$LBLUE$message$NC"
    return 0
}
